//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST10065470_RussellSchwedhelm_PROG7311_POE
{


    public partial class CreateItem
    {
    }
}
